### ISSUE TITLE
Github Action Failing

### ISSUE THREAD

**Issue by strenkml** [helfrichmichael/orcaslicer-novnc#10] opened 2023-10-03 14:05 UTC
The Github action that you have setup is failing which is causing the docker image to not be up to date. Orcaslicer made a change to the name of the Linux build so the get_release_info.sh script doesn't work anymore.

Here is a fork that someone made that fixes the issues: https://github.com/jamesdangercarpenter/orcaslicer-novnc

Could these changes be added to this repo?

**Comment by helfrichmichael** [comment] 2023-10-07 16:12
Ack, I'll work on getting these updated shortly. Need to review all the various GitHub issues this weekend.

**Comment by helfrichmichael** [comment] 2023-10-07 18:31
Dupe of https://github.com/helfrichmichael/orcaslicer-novnc/issues/6#issuecomment-1720347201

**Closed as not planned by helfrichmichael** 2023-10-07 18:31 UTC
Labels: bug, duplicate
